version: "3.8"
services:
    backend:
        container_name: django-backend
        build: ./backend
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend:/code
        ports:
            - "8000:8000"
    frontend:
        container_name: nuxt-frontend
        build: ./frontend
        command: npm run dev
        volumes:
            - ./frontend:/code
        ports:
            - "3000:3000"
